function frame = generateFrame_250fps()
% Frame types : heartbeat, plc and robot
frameTypes = { ...
    {'heartbeat', 1, 1}, ...
    {'plc', 50, 0.5}, ...
    {'robot', 50, 2} ...
    };
% Sample a random index
idx = randi(length(frameTypes));
% Construct frame
frame = Frame(frameTypes{idx}{2}, 0, frameTypes{idx}{3}*1000, frameTypes{idx}{1});
end