function frame = generateFrame_60fps()
% Frame types : arvr, camera and worker
frameTypes = { ...
    {'arvr', 50, 10}, ...
    {'camera', 1500, 2}, ...
    {'worker', 25000, 10} ...
    };
% Sample a random index
idx = randi(length(frameTypes));
% Construct frame
frame = Frame(frameTypes{idx}{2}, 0, frameTypes{idx}{3}*1000, frameTypes{idx}{1});
end