function frame = generateFrame()
% Frame types
frameTypes = { ...
    {'heartbeat', 1, 1}, ...
    {'plc', 50, 0.5}, ...
    {'robot', 50, 2}, ...
    {'arvr', 50, 10}, ...
    {'camera', 1500, 2}, ...
    {'worker', 25000, 10} ...
    };
% Sample a random index
idx = randi(length(frameTypes));
% Construct frame
frame = Frame(frameTypes{idx}{2}, 0, frameTypes{idx}{3}*1000, frameTypes{idx}{1});
end